name: CD

on:
  workflow_dispatch:

jobs:
  buildPackages:
    strategy:
      matrix:
        kind: ["linux", "windows", "macOS"]
        # kind: ["linux"]
        include:
          - kind: linux
            os: ubuntu-18.04
          - kind: windows
            os: windows-latest
          - kind: macOS
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.15.4
      - name: Install Deps
        run: |
          yarn install
      - name: Babel
        run: |
          yarn babel
      - name: Build
        env:
          MAKE_JOBS: 3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn start